{% set data = load_setup_py_data() %}

package:
  name: relate1k
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/relate1k.git

build:
  number: 0
  script: python -m pip install . -vv
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:  # your library dependencies
    - python
    # - jupyter
    # - ipython
    # - matplotlib>=3.0
    # - numpy>=1.1
    # - requests
    # - biopython
    # - goatools>=1.2
    # - pytables
    # - wget

channels:  # channels for your library dependencies
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build=24 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  
test:
  imports:
    - relate1k

about:
  home: https://github.com/munch-group/relate1k.git
  license: MIT
  dev_url: https://github.com/munch-group/relate1k.git
  doc_url: https://munch-group.org/relate1k
